name: BooleRegions
version: ${project.version}@${maven.build.timestamp}
main: eu.saltyscout.booleregion.plugin.BooleRegionPlugin
author: Peter Kramer
depend: [WorldEdit]
commands:
    clip:
        aliases: [/clip,clipboard,/clipboard]
        usage: //clip <list|select/load|copy/clone|save/store> [[owner:]id] [[owner:]id]
        permission: booleregion.command